name: example
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
#  background_fetch: ^1.0.3
#  shared_preferences: ^2.0.13
  curved_navigation_bar: ^1.0.3

dev_dependencies:
  build_runner:
  flutter_test:
    sdk: flutter



flutter:
  uses-material-design: true

